import type { Conversation, ConsensusResult } from "@/types";
import { mockAttestationHash } from "./utils";

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: "conv-001",
    subject: "Updated wire transfer instructions — Q3 vendor payment",
    participants: ["finance@acmecorp.com", "billing@apex-supplies.net"],
    lastActivity: new Date(Date.now() - 8 * 60_000).toISOString(),
    riskLevel: "critical",
    flaggedAt: new Date(Date.now() - 7 * 60_000).toISOString(),
    messageCount: 4,
    hasPaymentRequest: true,
    consensus: {
      verdict: "flag",
      confidence: 0.97,
      activeNodes: ["domain", "language", "behavior", "bank", "history"],
      votes: [
        { detectorId: "domain", verdict: "flag", confidence: 0.94, evidence: "apex-supplies.net registered 11 days ago. Legitimate domain apex-supplies.com exists and does not match." },
        { detectorId: "language", verdict: "flag", confidence: 0.91, evidence: "Urgency language ('before end of day', 'as discussed') present. Sender linguistic baseline mismatch on 3 stylometric markers." },
        { detectorId: "behavior", verdict: "flag", confidence: 0.99, evidence: "Wire transfer request from this sender is anomalous. No prior payment requests in 18-month history." },
        { detectorId: "bank", verdict: "flag", confidence: 0.98, evidence: "Destination account flagged in shared fraud intelligence feed. Beneficiary name mismatch with account history." },
        { detectorId: "history", verdict: "flag", confidence: 0.88, evidence: "Payment amount ($127,400) is 4.2× the median transaction for this vendor relationship." },
      ],
      attestationHash: mockAttestationHash(),
      timestamp: new Date(Date.now() - 7 * 60_000).toISOString(),
    },
  },
  {
    id: "conv-002",
    subject: "Invoice #8841 — August retainer",
    participants: ["ap@acmecorp.com", "hello@meridian-studio.io"],
    lastActivity: new Date(Date.now() - 2.5 * 3600_000).toISOString(),
    riskLevel: "medium",
    flaggedAt: new Date(Date.now() - 2.4 * 3600_000).toISOString(),
    messageCount: 6,
    hasPaymentRequest: true,
    consensus: {
      verdict: "flag",
      confidence: 0.72,
      activeNodes: ["domain", "language", "transaction", "identity"],
      votes: [
        { detectorId: "domain", verdict: "clear", confidence: 0.89, evidence: "Domain meridian-studio.io is 2.3 years old with consistent MX history." },
        { detectorId: "language", verdict: "uncertain", confidence: 0.55, evidence: "Moderate stylometric drift detected. Possibly authored by a different team member." },
        { detectorId: "transaction", verdict: "flag", confidence: 0.81, evidence: "Bank account differs from the account used for the previous 5 invoices from this vendor." },
        { detectorId: "identity", verdict: "flag", confidence: 0.77, evidence: "Signatory name 'James Reeve' not present in prior correspondence. Usual contact is 'Sarah Chen'." },
      ],
      attestationHash: mockAttestationHash(),
      timestamp: new Date(Date.now() - 2.4 * 3600_000).toISOString(),
    },
  },
  {
    id: "conv-003",
    subject: "Re: Renewal quote — SaaS subscription",
    participants: ["ops@acmecorp.com", "renewals@vendor-platform.com"],
    lastActivity: new Date(Date.now() - 5 * 3600_000).toISOString(),
    riskLevel: "low",
    messageCount: 9,
    hasPaymentRequest: false,
    consensus: {
      verdict: "clear",
      confidence: 0.93,
      activeNodes: ["domain", "behavior", "relationship", "language"],
      votes: [
        { detectorId: "domain", verdict: "clear", confidence: 0.98, evidence: "Established domain, 6-year history, DMARC/DKIM pass." },
        { detectorId: "behavior", verdict: "clear", confidence: 0.91, evidence: "Communication pattern consistent with 3-year vendor relationship." },
        { detectorId: "relationship", verdict: "clear", confidence: 0.95, evidence: "Sender verified in organizational trust graph with 14 prior interactions." },
        { detectorId: "language", verdict: "clear", confidence: 0.87, evidence: "Language consistent with established communication style for this contact." },
      ],
      attestationHash: mockAttestationHash(),
      timestamp: new Date(Date.now() - 5 * 3600_000).toISOString(),
    },
  },
  {
    id: "conv-004",
    subject: "URGENT: CEO approval needed for acquisition transfer",
    participants: ["cfo@acmecorp.com", "m.hartwell@acmecorp-group.co"],
    lastActivity: new Date(Date.now() - 14 * 60_000).toISOString(),
    riskLevel: "critical",
    flaggedAt: new Date(Date.now() - 13 * 60_000).toISOString(),
    messageCount: 2,
    hasPaymentRequest: true,
    consensus: {
      verdict: "flag",
      confidence: 0.99,
      activeNodes: ["domain", "language", "behavior", "device", "identity"],
      votes: [
        { detectorId: "domain", verdict: "flag", confidence: 0.99, evidence: "acmecorp-group.co is a typosquat of acmecorp.com. Registered yesterday via privacy proxy." },
        { detectorId: "language", verdict: "flag", confidence: 0.96, evidence: "Classic BEC pattern: executive impersonation, secrecy request, time pressure. 97th percentile urgency score." },
        { detectorId: "behavior", verdict: "flag", confidence: 0.99, evidence: "No prior communication from this address. CEO has no history of initiating wire requests via email." },
        { detectorId: "device", verdict: "flag", confidence: 0.93, evidence: "Originating IP geolocated to Eastern Europe. No VPN or corporate infrastructure detected." },
        { detectorId: "identity", verdict: "flag", confidence: 0.99, evidence: "Display name spoofs CEO. DMARC fails. SPF record not aligned." },
      ],
      attestationHash: mockAttestationHash(),
      timestamp: new Date(Date.now() - 13 * 60_000).toISOString(),
    },
  },
  {
    id: "conv-005",
    subject: "PO #2291 — materials shipment confirmation",
    participants: ["procurement@acmecorp.com", "logistics@steelframe-co.com"],
    lastActivity: new Date(Date.now() - 18 * 3600_000).toISOString(),
    riskLevel: "clear",
    messageCount: 12,
    hasPaymentRequest: false,
  },
];

export const MOCK_MAILBOX_HEALTH = {
  monitored: 847,
  flagged: 3,
  cleared: 61,
  pendingReview: 2,
};
